require('dotenv').config();
const express=require('express');
const cors=require('cors');
const connectDB=require('./config/db');
const app=express();
app.use(cors());
app.use(express.json());
connectDB();
app.use('/api/auth', require('./routes/auth'));
app.use('/api/lsp', require('./routes/lsp'));
app.use('/api/requests', require('./routes/request'));
app.get('/',(req,res)=>res.json({message:'Backend running...'}));
app.listen(process.env.PORT||5000,()=>console.log('Server running'));
